# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=120, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Comercializar'), (1, 'Compuesto'), (1, 'Materia prima')])),
                ('iva', models.BooleanField(default=False, verbose_name='Grabado con iva')),
                ('ipoconsumo', models.BooleanField(default=False, verbose_name='Impoconsumo')),
                ('precio_venta', models.FloatField(verbose_name='Precio de venta')),
                ('adquisicion', models.FloatField(verbose_name='Precio de compra')),
                ('rentabilidad', models.FloatField(verbose_name='Porcentaje de rentabilidad')),
                ('rentabilidad_ingreso', models.FloatField(verbose_name='Porcentaje de rentabilidad sobre ingreso')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='ComposicionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Activo')),
            ],
            options={
                'verbose_name': 'Descripci\xf3n composicion de articulo',
                'verbose_name_plural': 'Entradas de articulos',
            },
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc_art', to='inventario.Activo')),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ComposicionProducto')),
            ],
            options={
                'verbose_name': 'Descripci\xf3n composicion de articulo',
                'verbose_name_plural': 'Entradas de articulos',
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('valor', models.FloatField(default=0)),
                ('realizacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salida de articulo',
                'verbose_name_plural': 'Salidas de articulos',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de negocio',
                'verbose_name_plural': 'Unidades de negocios',
            },
        ),
        migrations.CreateModel(
            name='UnidadNegocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de negocio',
                'verbose_name_plural': 'Unidades de negocios',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('salida_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.Salida')),
                ('cantidad_e', models.FloatField(default=0)),
                ('valor_e', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Entrada de articulo',
                'verbose_name_plural': 'Entradas de articulos',
            },
            bases=('inventario.salida',),
        ),
        migrations.AddField(
            model_name='salida',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Activo'),
        ),
        migrations.AddField(
            model_name='activo',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.UnidadNegocio'),
        ),
        migrations.AddField(
            model_name='activo',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Unidad'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='activo_e',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Activo'),
        ),
    ]
