# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicionproducto',
            name='desc',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripci\xf3n'),
        ),
    ]
