# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_cajero_autenticate'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleados.UnidadNegocio'),
            preserve_default=False,
        ),
    ]
