# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20170616_0758'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='articulos',
            field=models.ManyToManyField(to='inventario.Activo'),
        ),
    ]
