# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_auto_20170621_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajero',
            name='negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleados.UnidadNegocio', verbose_name='Unidad de negocio'),
            preserve_default=False,
        ),
    ]
