# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor'),
            preserve_default=False,
        ),
    ]
