# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_auto_20170616_1917'),
        ('inventario', '0002_auto_20170616_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('valor_unitario', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Activo')),
            ],
            options={
                'verbose_name': 'Descripcion factura',
                'verbose_name_plural': 'Descripciones de Facturas',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.FloatField(default=0)),
                ('iva', models.FloatField(default=0)),
                ('impoconsumo', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Ciente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.AddField(
            model_name='detalle',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Factura'),
        ),
    ]
