# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pago',
            field=models.IntegerField(choices=[(1, 'Contado'), (2, 'Credito')], default=1, verbose_name='Tipo de pago'),
            preserve_default=False,
        ),
    ]
