# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20170616_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='paga',
            field=models.BooleanField(default=False),
        ),
    ]
